### ISSUE TITLE
Flashing Sign In Button

### ISSUE THREAD

**Issue by decaf-dev** [byuweb/byu-user-info-oauth#2]
Using v2 of the BYU header and footer components in React.js and the lastest version of the byu-user-info-oauth the sign in button will momentarily be at the left side and then jump to the right side of the screen.

Reproduce:
![image](https://user-images.githubusercontent.com/40307803/74995411-119d0580-540e-11ea-91b1-a2a5f2daadc1.png)

![image](https://user-images.githubusercontent.com/40307803/74995435-2083b800-540e-11ea-89e2-12ad9ce89c31.png)

![image](https://user-images.githubusercontent.com/40307803/74995498-4c9f3900-540e-11ea-87ee-9504cfb3c6d8.png)

**Comment by snelg** [comment]
Not an issue with this component directly.
In your example code, try changing
```html
<byu-user-info-oauth slot="user"></byu-user-info-oauth>
```
with
```html
<div slot="user" style="color: white">I'M A LITTLE TEAPOT</div>
```
The same jumping occurs.
So it's an issue with how the BYU Theme component handles the "user" slot during initial render.

Here's a kludgy little workaround if you don't want to wait for the Theme component maintainers to address this. Add this somewhere in `<head>`, or wherever you load your stylesheets:
```css
<style type="text/css">
  byu-user-info-oauth {
    display: none;
  }
  .byu-component-rendered byu-user-info-oauth {
    display: block;
  }
</style>
```
That will completely hide the `byu-user-info-oauth` piece until after the Theme component code has finished building the `byu-header`. After that code finishes, it adds that `byu-component-rendered` class to the `byu-header`
